//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.14 at 09:02:21 �ߌ� JST
//


package org.jenkinsci.plugins.vs_code_metrics.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Targets" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Version" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "targets"
})
@XmlRootElement(name = "CodeMetricsReport")
public class CodeMetricsReport {

    @XmlElement(name = "Targets")
    protected Targets targets;
    @XmlAttribute(name = "Version", required = true)
    protected double version;

    /**
     * Gets the value of the targets property.
     *
     * @return
     *     possible object is
     *     {@link Targets }
     *
     */
    public Targets getTargets() {
        return targets;
    }

    /**
     * Sets the value of the targets property.
     *
     * @param value
     *     allowed object is
     *     {@link Targets }
     *
     */
    public void setTargets(Targets value) {
        this.targets = value;
    }

    /**
     * Gets the value of the version property.
     *
     */
    public double getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     */
    public void setVersion(double value) {
        this.version = value;
    }

}
