//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.14 at 09:02:21 �ߌ� JST
//


package org.jenkinsci.plugins.vs_code_metrics.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Metrics" minOccurs="0"/>
 *         &lt;element ref="{}Namespaces" minOccurs="0"/>
 *         &lt;element ref="{}Types" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metrics",
    "namespaces",
    "types"
})
@XmlRootElement(name = "Module")
public class Module {

    @XmlElement(name = "Metrics")
    protected Metrics metrics;
    @XmlElement(name = "Namespaces")
    protected Namespaces namespaces;
    @XmlElement(name = "Types")
    protected Types types;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the metrics property.
     *
     * @return
     *     possible object is
     *     {@link Metrics }
     *
     */
    public Metrics getMetrics() {
        return metrics;
    }

    /**
     * Sets the value of the metrics property.
     *
     * @param value
     *     allowed object is
     *     {@link Metrics }
     *
     */
    public void setMetrics(Metrics value) {
        this.metrics = value;
    }

    /**
     * Gets the value of the namespaces property.
     *
     * @return
     *     possible object is
     *     {@link Namespaces }
     *
     */
    public Namespaces getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     *
     * @param value
     *     allowed object is
     *     {@link Namespaces }
     *
     */
    public void setNamespaces(Namespaces value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the types property.
     *
     * @return
     *     possible object is
     *     {@link Types }
     *
     */
    public Types getTypes() {
        return types;
    }

    /**
     * Sets the value of the types property.
     *
     * @param value
     *     allowed object is
     *     {@link Types }
     *
     */
    public void setTypes(Types value) {
        this.types = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

}
