//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.14 at 09:02:21 �ߌ� JST
//


package org.jenkinsci.plugins.vs_code_metrics.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the generated package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Module }
     *
     */
    public Module createModule() {
        return new Module();
    }

    /**
     * Create an instance of {@link Namespace }
     *
     */
    public Namespace createNamespace() {
        return new Namespace();
    }

    /**
     * Create an instance of {@link Namespaces }
     *
     */
    public Namespaces createNamespaces() {
        return new Namespaces();
    }

    /**
     * Create an instance of {@link CodeMetricsReport }
     *
     */
    public CodeMetricsReport createCodeMetricsReport() {
        return new CodeMetricsReport();
    }

    /**
     * Create an instance of {@link Metric }
     *
     */
    public Metric createMetric() {
        return new Metric();
    }

    /**
     * Create an instance of {@link Targets }
     *
     */
    public Targets createTargets() {
        return new Targets();
    }

    /**
     * Create an instance of {@link Members }
     *
     */
    public Members createMembers() {
        return new Members();
    }

    /**
     * Create an instance of {@link Types }
     *
     */
    public Types createTypes() {
        return new Types();
    }

    /**
     * Create an instance of {@link Modules }
     *
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Member }
     *
     */
    public Member createMember() {
        return new Member();
    }

    /**
     * Create an instance of {@link Metrics }
     *
     */
    public Metrics createMetrics() {
        return new Metrics();
    }

    /**
     * Create an instance of {@link Target }
     *
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Type }
     *
     */
    public Type createType() {
        return new Type();
    }

}
